version: '3'

services:

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always    
    tty: true
    networks:
      - node-network
    ports:      
      - "8080:80"
    depends_on: 
      - nodeserver

  nodeserver:
    build:
      context: node
    container_name: nodeserver
    restart: always    
    networks:
      - node-network    
    tty: true    
    depends_on:
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    command: --init-file /data/application/init.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db/init.sql:/data/application/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge